[package]
name = "polar_cleaner"
version = "0.1.0"
edition = "2021"

[dependencies]
polars = {version ="0.38.4", features = ["csv", "parquet", "lazy", "dtype-u8", "performant"]}
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
