[package]
name = "quantization_model"
version = "0.1.0"
edition = "2024"

[dependencies]
candle-core = "0.9.1"
candle-nn = "0.9.1"
candle-transformers = "0.9.1"
csv = "1.4.0"
ndarray = "0.17.1"
rand = "0.9.2"
